# GitHub Actions workflow for running Selenium Python tests
name: run selenium with pytest

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        
        - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: '3.13'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r automation_framework/requirements.txt

        - name: Install Chrome browser
          uses: browser-actions/setup-chrome@v1 
        
        - name: Run tests
          run: pytest -m smoke --html=report.html --self-contained-html automation_framework/tests/
        
        - name: Upload Test Report
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: test-report
            path: report/report.html
